publishDir: docs
baseURL: "https://cyberhippo.github.io/cuizizine"
disablePathToLower: true
languageCode: fr-fr
title: Cuizizine
theme: gochowdown
googleAnalytics:
defaultcontentlanguage: en
paginate: 6
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: CyberHippo
  github: CyberHippo
  description: Nos meilleures recettes !
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent: "'Manger, c'est important.' - A. Einstein"
  hidecredits: false
  hidecopyright: false
  showNavTitle: true            # Boolean: show site title in nav bar
  custom_css:
    - style.css
menu:
  main:
    - name: Accueil
      weight: 1
      url: /
    - name: Categories
      weight: 2
      url: /categories/
    - name: Cuisine
      weight: 3
      url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/
taxonomies:
  category: categories
  cusine: cuisine
  tag: tags
