name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs
          cname: cuizizine.vergnol.eu
